### PR TITLE
allow constraining display value to inputRange

### PR DESCRIPTION
**Pull request by Resseguie**
Just a suggested addition to options. Truncates raw value that is displayed to fit within the specified inputRange.

### CODE REVIEW

**Comment by dtex** [comment]
Cool, thank you!

I was thinking about leaving red out of the color rotation and if the input values exceeded the range then I would turn that bar red. What do you think?

**Comment by Resseguie** [comment]
I don't think you should take out red. There are times when red would the be logically correct color to use for certain displayed values. (Tracking number of errors, for example?)

But you could potentially chalk the raw value at the end red in that case as an alternative?

**Comment by Resseguie** [comment]
@dtex ^^
(Don't know if it shows up in activity for closed PR...)

**Comment by dtex** [comment]
It did show up. I like that suggestion. I'll have it display the value in red if it is outside the range. Added issue #2

**Pull request merged**
